добавил тесты негативные и обработку ошибок
gorushkin/backend-project-lvl3 pull request #10
Opened 2020-12-02 13:23 UTC by gorushkin

2020-12-02 20:27 UTC, foofaev requested changes

2020-12-02 20:27 UTC, foofaev commented on __tests__/page-loader.test.js
> +  });
jest предоставляет встроенные способы проверки ошибок - [expect().toThrow()](https://jestjs.io/docs/ru/expect#tothrowerror)

2020-12-02 20:27 UTC, foofaev commented on __tests__/page-loader.test.js
> +  test('output folder is not exist', async () => {
doesn't

2020-12-02 20:27 UTC, foofaev commented on __tests__/page-loader.test.js
> +      expect(error.code).toEqual('ENOENT');
если бы тест был на проверку именно папки, то бросило бы enotdir

2020-12-02 20:27 UTC, foofaev commented on __tests__/page-loader.test.js
>    });
стоит добавить:
- тесты на ответ от нормального сайта с ошибкой (400-е, 500-е). 
- тест с сохранением данных в папку, к которой нет доступа (рут)
- тест на отстуствующую папку

2020-12-02 20:27 UTC, foofaev commented on src/bin/page-loader.js
> +      .catch((error) => errorMapping[error.code](error));
все-таки это бинарник. тут можно поймать ошибку, только чтобы ее сразу вывести на экран. логика должна быть в коде. еще тут не хватает дефолтного кейса

2020-12-03 12:27 UTC, gorushkin commented on __tests__/page-loader.test.js
> +      expect(error.code).toEqual('ENOENT');
Ну я по-всякому пробовал. Все время кидает ENOENT. 
ENOENT (No such file or directory): Commonly raised by fs operations to indicate that a component of the specified pathname does not exist. No entity (file or directory) could be found by the given path.
Да и кажется у меня проверка, не тест, какая-то дурацкая

2020-12-03 21:17 UTC, foofaev commented on __tests__/page-loader.test.js
> +      expect(error.code).toEqual('ENOENT');
да, что-то я тоже неправильно написал. чтобы поймать enotdir, надо чтобы путь до папки был на самом деле путем до файла

2020-12-03 21:24 UTC, foofaev requested changes

2020-12-03 21:24 UTC, foofaev commented on src/errorHandler.js
> +  error.message = errorMapping[error.code] ? errorMapping[error.code](error) : 'Unexpected error occurred';
так-то мы перехватили ту ошибку. значит, ее больше нет. стоит новую создать, свою
в доках есть, как это сделать https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

2020-12-03 21:24 UTC, foofaev commented on src/index.js
> +import errorHandler from './errorHandler';
функция должна быть глаголом. имя модуля должно быть равно имени функции, экспортируемой из этого модуля по-умолчанию (https://github.com/airbnb/javascript#naming-conventions)

2020-12-07 21:05 UTC, foofaev requested changes

2020-12-07 21:05 UTC, foofaev commented on src/FriendlyError.js
> +  const errorMapping = {
ниже в названии уточняется, что за errorMapping, а тут нет.

2020-12-07 21:05 UTC, foofaev commented on src/FriendlyError.js
> +      : error.message;
странно, что линтер тут ошибку не выдал. это useless ternary, можно записать как networkErrorMapping[error.response.status] || error.message;

2020-12-07 21:05 UTC, foofaev commented on src/FriendlyError.js
> +  };
нет смысла деражть маппинги внутри функции и усложнять ее этим

2020-12-07 21:05 UTC, foofaev commented on .eslintrc.yml
> +  no-param-reassign: ["error", { "props": true, "ignorePropertyModificationsFor": ["item", "error"] }]
это уже не нужно

2020-12-07 21:05 UTC, foofaev commented on __tests__/page-loader.test.js
> +    nock('https://ru.hexlet.io/')
повторяется в каждом тесте

2020-12-07 21:05 UTC, foofaev commented on __tests__/page-loader.test.js
> +  beforeEach(async () => {
это дернется раньше теста сверху в любом случае. поэтому стоит наверху складывать любоые before

2020-12-07 21:05 UTC, foofaev commented on __tests__/page-loader.test.js
> +    tempDir = '/tmp/tmp2/';
что-то как-то это ненадежно. как минимум стоит до вызова expect проверить, что эта папка реально не существует (fs.access.catch)

2020-12-07 21:05 UTC, foofaev commented on __tests__/page-loader.test.js
> +const errorTestsData = [
это тестовые данные для ошибок сетевых запросов. стоит это уточнить в названии

2020-12-07 21:05 UTC, foofaev commented on src/FriendlyError.js
> +}
мы тут совсем не используем информацию об ошибке из реквеста. обычно там бывает полезная информация, о том, в чем именно проблема

2020-12-10 06:02 UTC, merged