Issue 2
gorushkin/backend-project-lvl3 pull request #7
Opened 2020-11-22 19:33 UTC by gorushkin

2020-11-23 17:59 UTC, foofaev requested changes

2020-11-23 17:59 UTC, foofaev commented on __tests__/page-loader.test..js
>    'ru-hexlet-io-assets-professions-img01.jpg',
у файла две точки перед расширением

2020-11-23 17:59 UTC, foofaev commented on __tests__/page-loader.test..js
> +});
все тесты почти полностью повторяют друга друга, стоит это обобщить через tests.each

2020-11-23 17:59 UTC, foofaev commented on src/index.js
> +const IsElementSourceLocal = (src, url) => {
опять функция - не конструктор с большой буквы

2020-11-23 17:59 UTC, foofaev commented on src/getEncodedHtml.js
> +export default (string) => iconv.decode(string, getSourceEncoding(jschardet.detect(string)));
непонятно, чем порождена необходимость такого декодинга

2020-11-23 17:59 UTC, foofaev commented on src/index.js
> +const isTagCanonical = (tag) => tag === 'canonical';
это [код, который убивает полиморфизм](https://ru.hexlet.io/courses/js-polymorphism/lessons/breaking-polymorphism/theory_unit)

2020-11-23 17:59 UTC, foofaev commented on src/index.js
> +        const name = isTagCanonical(elem.attribs.rel) ? `${getElementName(source)}.html` : getElementName(source);
а если не canonical, то не может быть html?

2020-11-23 17:59 UTC, foofaev commented on src/index.js
> +};
совсем не понимаю, что делает эта функция

2020-11-23 17:59 UTC, foofaev commented on src/index.js
> +  return true;
```
> new URL('http://hexlet.io/courses', 'http://hexlet.io')
URL {
  href: 'http://hexlet.io/courses',
  origin: 'http://hexlet.io',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'hexlet.io',
  hostname: 'hexlet.io',
  port: '',
  pathname: '/courses',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
> new URL('/courses', 'http://hexlet.io')
URL {
  href: 'http://hexlet.io/courses',
  origin: 'http://hexlet.io',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'hexlet.io',
  hostname: 'hexlet.io',
  port: '',
  pathname: '/courses',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
> new URL('http://google.com/search', 'http://hexlet.io')
URL {
  href: 'http://google.com/search',
  origin: 'http://google.com',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'google.com',
  hostname: 'google.com',
  port: '',
  pathname: '/search',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}

```

2020-11-23 17:59 UTC, foofaev commented on src/index.js
> +  && elementSource !== url.href;
тут и в других местах нам не нужен объект урлы, нам нужна строка из него. причем, скорей всего только origin

2020-11-23 17:59 UTC, foofaev commented on src/index.js
> +  return fs.promises.writeFile(filePath, html.html(), 'utf-8').then(() => sources);
getSources в виде сайдэффекта качает файл на диск. это нарушение принципа чистой функции.

2020-11-23 17:59 UTC, foofaev commented on src/index.js
> +    .then((list) => downloadElements(list, assetsFolderPath))
в данном случае, возможно, что нет смысла передавать в функцию набор элементов, потому что у нас все в одном модуле и забором ссылок занимается не отдельный сервис, который умеет парсить любые ссылки, а просто функция, которую мы вынесли для удобства в модуль

2020-11-23 17:59 UTC, foofaev commented on src/index.js
> +    responseType: 'arraybuffer',
а зачем нам это тут?

2020-11-24 18:52 UTC, foofaev requested changes

2020-11-24 18:52 UTC, foofaev commented on __tests__/page-loader.test.js
> +});
теперь код не повторяется, отлично!
но он все еще разбросан, что затрудняет читабельность.

было бы хорошо, если тестовые данные были в одном месте рядом друг с другом. для этого можно использовать уже готовый массив tests, но в нем создать коллекцию из объектов. каждый объект - тестовые данные для конкретного формата (формат, ожидаемые пути, тестовые пути, урлы)

2020-11-24 18:52 UTC, foofaev commented on __fixtures__/ru-hexlet-io-courses--output.html
>  <head>
ожидаемые данные лучше бы так и называть "expected..."

2020-11-24 18:52 UTC, foofaev commented on src/index.js
> +};
этот маппинг (необходимость его сущестования) все еще смущает меня.видов линков очень [много](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types), а мы выделяем только один. Предлагаю просто если у файла нет расширения, то считать, что это html

2020-11-24 18:52 UTC, foofaev commented on src/index.js
> +    const itemSrcAttribute = elements[itemName];
использование Object.entries помогло бы избавиться от дополнительного получения этой константы

2020-11-24 18:52 UTC, foofaev commented on src/index.js
> +        const itemSource = (new URL(html(elem).attr(itemSrcAttribute), url)).href;
вне зависимости от фильтрации нам нужно всегда получать нужный атрибут и паковать его в new URL(атрибут, сайт). такой маппинг до фильтрации упростил бы фильтрацию до 
```  
filter(({ url }) => url.origin === website);
```

и убрал бы дублирование кода ниже

2020-11-24 18:52 UTC, foofaev commented on src/index.js
> +        const itemType = html(elem).attr('rel') === 'canonical' ? 'hyperlink' : 'usual';
на этот счет написал выше про маппинг

2020-11-24 18:52 UTC, foofaev commented on src/index.js
>  const createAssetsFolder = (assetsFolderPath) => fs
гугл хром при скаче страницы создает папку сам, если ее нет

2020-11-24 18:52 UTC, foofaev commented on src/index.js
> +const getSource = (itemSource, { href }) => {
странно передавать целый объект и забирать из него один параметр

2020-11-24 18:52 UTC, foofaev commented on src/index.js
> +  return (new URL(path.join(href, itemSource))).href;
я вчера тебя сильно обманул
```
> new URL('../a.js', 'http://hexlet.io/courses/index.html')
URL {
  href: 'http://hexlet.io/a.js',
  origin: 'http://hexlet.io',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'hexlet.io',
  hostname: 'hexlet.io',
  port: '',
  pathname: '/a.js',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}

```

2020-11-25 19:19 UTC, foofaev requested changes

2020-11-25 19:19 UTC, foofaev commented on __tests__/page-loader.test.js
> +      expectedJs: await fs.promises.readFile(getFilePath(testData.js.inputFilename)),
если использовать синхронные методы, то можно это положить в тот красивый массив

2020-11-25 19:19 UTC, foofaev commented on __tests__/page-loader.test.js
> +  ];
по факту, нам только формат надо, остальное получится из testData[format]

2020-11-25 19:19 UTC, foofaev commented on src/index.js
> +const isOutputPathExist = (output) => fs.promises.stat(output);
функция предикат (которые возвращают по определению true|false) обращается к файлу и как сайд-эффект бросает ошибку. для проверки доступа есть fs.access. но вообще говоря, при попытке записи туда ошибка сама бросится

2020-11-25 19:19 UTC, foofaev commented on src/index.js
> +  .promises.mkdir(assetsFolderPath, { recursive: true });
а теперь она бросит ошибку, если папка есть (стоит сначала тыкнуть в нее fs.access-ом)

2020-11-25 19:19 UTC, foofaev commented on src/index.js
> +  const result = isUrlAbsolute(str) ? str : str.replace(/^\//i, '');
что-то меня это смущает. если урла начинается с двойного слэша - это баг скорей всего (https://sitebulb.com/hints/internal/url-contains-a-double-slash/)

2020-11-25 19:19 UTC, foofaev commented on src/index.js
> +  const result = isUrlAbsolute(str) ? str : str.replace(/^\//i, '');
и зачем нам его обрабатывать

2020-11-25 19:19 UTC, foofaev commented on src/index.js
>  const getPath = (arg1, arg2) => path.join(arg1, arg2);
функция делает просто path.join, есть ли смысл выделять отдельную функцию?

2020-11-25 19:19 UTC, foofaev commented on src/index.js
> +        const name = isLinkHasExtension(src.href) ? (getElementName(src.href)) : `${(getElementName(src.href))}.html`;
есть тут смысл собирать название, если мы это не используем, пока не дойдем до сборки пути?
и, наверно, лучше выставление расширения лучше выделить в функцию сборки имени файла (кстати, собираем не имя элемента же, а имя файла)

2020-11-25 19:19 UTC, foofaev commented on src/index.js
> +        const { name } = item;
map({src, name}) ?

2020-11-25 19:19 UTC, foofaev commented on src/index.js
> +  const sources = Object.entries(elements).reduce((acc, [itemName, itemSrcAttribute]) => {
а точно тут reduce нужен? был массив, остался массив

2020-11-26 12:50 UTC, gorushkin commented on src/index.js
> +        const { name } = item;
Тут у меня еще сразу после сборки имени файла в cheerio объекте заменяются пути к файлам?
```html(item).attr(itemSrcAttribute, path.join(assetsFolderName, filename));```

2020-11-26 13:04 UTC, gorushkin commented on src/index.js
> +  const sources = Object.entries(elements).reduce((acc, [itemName, itemSrcAttribute]) => {
Так массив же  начальный размера 3. 
```
const elements = {
  img: 'src',
  link: 'href',
  script: 'src',
};
```
Можно получить вообще все элементы  селектором *
 `$('*').toArray().filter(по типу и по локальности ссылки)).map.(собираем имена)`

Как лучше сделать тогда?

2020-11-26 13:10 UTC, gorushkin commented on src/index.js
> +  .promises.mkdir(assetsFolderPath, { recursive: true });
Я не знаю как утилита должна себя вести. Если нет папки DOWNLOADS указанной юзером `page-loader --output downloads http....`, то утилита не должна ничего писать, а выкинуть ошибку, которую мы обработаем. Если же папка есть, то мы создаем там папку с ассетами. Это понятно. Но если папка с ассетами уже есть, то как надо себя вести? перезаписать или сказать, что там занято и выкинуть ошибку?

2020-11-27 05:29 UTC, foofaev commented on src/index.js
> +  .promises.mkdir(assetsFolderPath, { recursive: true });
тут можно сделать так:
- пользователь передал путь /home/folder1/folder2/
- папка folder2 не существует
- мы собрали путь  /home/folder1/folder2/assets/
- fs.mkdir отвалится, если папки folder2 нет
- fs.mkdir(path, {recursive: true}) досоздаст папки

Поэтому мы в безопасности, если не используем recursive (не насоздаем левых путей)

2020-11-27 05:29 UTC, foofaev commented on src/index.js
> +  const sources = Object.entries(elements).reduce((acc, [itemName, itemSrcAttribute]) => {
это я не подумал, не надо переписывать

2020-11-27 05:29 UTC, foofaev commented on src/index.js
> +        const { name } = item;
точно, но мы это делаем несколько раз, кажется. может один раз мапом собрать, а потом уже передавать в объекте?

2020-11-28 18:14 UTC, foofaev requested changes

2020-11-28 18:14 UTC, foofaev commented on src/index.js
> +const getElementFilename = (href) => (path.extname(href) ? (getElementName(href)) : `${(getElementName(href))}.html`);
может, проще расширение выставлять тоже в getElementName? мы там все равно ставим, если есть. пусть и дефолтный ставится. причем это можно сделать изящно через: const { extname = 'html', pathname } = path.parse(filename);

2020-11-28 18:14 UTC, foofaev commented on src/index.js
> +        const source = (new URL(html(item).attr(itemSrcAttribute), url.href)).href;
рtml(item).attr(itemSrcAttribute)
мы это делаем и тут, и выше. может, если сначала обойти элементы мапом, который это делает, будет проще? а потом уже фильтр и пересборка пути?

2020-11-28 18:14 UTC, foofaev commented on src/index.js
> +        const source = (new URL(html(item).attr(itemSrcAttribute), url.href)).href;
да и в объект собранную урлу можно положить там же ({domElement, url})

2020-11-30 10:37 UTC, merged

2020-11-30 21:13 UTC, foofaev commented on src/index.js
> +    .then((html) => getSources(html, targetUrl, assetsFolderName))
все-таки у нас тут уже распаршенный дом, а не html.
а урлу достаточо прокинуть targetURL.origin. больше ничего мы не используем, но при этом обращаемся по ключам к урле. усложняет

2020-11-30 21:13 UTC, foofaev commented on src/index.js
> +    .then(([html, sources]) => downloadElements(html, sources, assetsFolderPath, filePath))
папку мы уже опрокинули в предыдущую функцию и там собрали полный путь . а тут повторяемся

2020-11-30 21:13 UTC, foofaev commented on src/index.js
> +          url: path.join(assetsFolderName, filename),
ну все-таки это не url же

2020-11-30 21:13 UTC, foofaev commented on src/index.js
> +      .filter(({ source }) => isSourceLocal(source, url));
сначала собрав, потом отфильтровав, мы немного нарушаем логику. вот если мы сначала соберем урлу только, а потом отфильтруем, тогда будет понятно, мы не можем отфильтровать, не собрав урулу. а потом можно уже вторым мапом обойти и собрать уже нужные элементы

2020-11-30 21:13 UTC, foofaev commented on src/index.js
> +    html(item).attr(item.tag, item.url);
нехорошо, что мы при загурзке еще и дом мутируем. лучше такие вещи держать в одном месте. у нас же достаточно данных в getSources, чтобы там все заменить и оставить только урлу и путь файла для загрузки

2020-11-30 21:13 UTC, foofaev commented on src/index.js
>  const updateName = (url) => {
все-таки мы тут ничего не обновляем, а собирем новое. правильно то, что мы делаем (результат), называется [slug](https://ru.wikipedia.org/wiki/%D0%A1%D0%B5%D0%BC%D0%B0%D0%BD%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_URL#Slug)

2020-11-30 21:13 UTC, foofaev commented on src/index.js
> +          url: path.join(assetsFolderName, filename),
url это source

2020-11-30 21:13 UTC, foofaev commented on src/index.js
> +  const { ext, name } = path.parse(source);
path.parse же dir тоже выдает. префикс тогда сам соберется.