переделал все
gorushkin/backend-project-lvl3 pull request #9
Opened 2020-12-01 05:52 UTC by gorushkin

2020-12-01 20:24 UTC, foofaev requested changes

2020-12-01 20:24 UTC, foofaev commented on src/index.js
> +  const namePrefix = getSlugName(dir);
а нам из имени, разве, не надо тоже убирать все лишние символы? кажется, стоит туда опрокидывать больше данных

2020-12-01 20:24 UTC, foofaev commented on src/index.js
> +        return { ...item, source };
не вижу, чтобы мы использовали что-то из item

2020-12-01 20:24 UTC, foofaev commented on src/index.js
>    const { host, pathname } = new URL(url);
что-то не очень хорошо, что функция знает, как парсить входящие данные (в частности, выбирать, какие данные взять, а какие нет). и не уверен, что это нужно. если у нас чистая функция, то она принимает строку и делает из нее слаг

2020-12-01 20:24 UTC, foofaev commented on src/index.js
> +const isSourceLocal = (source, url) => (new URL(source, url)).origin === url;
new URL(source, url) мы уже сделали ниже

2020-12-01 20:24 UTC, foofaev commented on src/index.js
> +        parsedDom(item).attr(itemSrcAttribute, path.join(assetsFolderName, filename));
itemPath уже собрали

2020-12-02 07:40 UTC, gorushkin commented on src/index.js
> +        parsedDom(item).attr(itemSrcAttribute, path.join(assetsFolderName, filename));
Не. смотри
filename - это просто ru-hexlet-io-courses.jpg'
Еще есть assetsFolderName - 'ru-hexlet-io-courses_files'
В HtmlDOM я записываю   'ru-hexlet-io-courses_files/ru-hexlet-io-courses.jpg'
itemPath - это абсолютный путь для файла. нужен для записи файла. его формирование я перенес в ф-цию скачивания файлов - '/home/...,бла-бла .../ru-hexlet-io-courses_files/ru-hexlet-io-courses.jpg'

2020-12-02 20:44 UTC, foofaev requested changes
почти идеально! правда
чуть-чуть подполируем только

2020-12-02 20:44 UTC, foofaev commented on src/index.js
>    const assetsFolderPath = path.join(pathToProject, assetsFolderName);
нехорошо, что у нас логика сборки имени отличается тут от той, которую делаем в ассетах. я понял, что это ради того, чтобы не повторять projectname =, но в плане поддержки и читабельности кода, лучше бы , чтобы одни и те же функции отвечали за один и тот же функционал

2020-12-02 20:44 UTC, foofaev commented on src/index.js
> +        return { ...item, source };
нехорошо, что мы тут делаем дестракчеринг. будто подменяем какое-то значение в итеме, хотя на самом деле ниже используем их по-отдельности. это путает

2020-12-02 20:44 UTC, foofaev commented on src/index.js
> +const getSources = (parsedDom, url, assetsFolderName) => {
хочется более конкретноеслово ,чем url. чтобы было понятно, что за урла пришла

2020-12-02 20:44 UTC, foofaev commented on src/index.js
> +        const source = (new URL(item.attribs[itemSrcAttribute], url));
source для картинки и скрипта подходят, да. а у линка это href. может, лучше тут использовать слово url?

2020-12-02 20:44 UTC, foofaev commented on src/index.js
> +        parsedDom(item).attr(itemSrcAttribute, path.join(assetsFolderName, filename));
теперь смущает, что доступ к одному и тому же значению, мы делаем двумя разнми способами. не нужно исправлять, но нужно учитывать, что ментор может это забраковать. но это не точно)

2020-12-02 20:44 UTC, foofaev commented on src/index.js
> +        parsedDom(item).attr(itemSrcAttribute, path.join(assetsFolderName, filename));
item.source.href
повторяется два раза. использовать бы дестракчеринг тут

2020-12-03 11:24 UTC, gorushkin commented on src/index.js
> +        return { ...item, source };
Так тут мы не подменяем, а добавляем свойство source к item'у. А потом ниже используем значение item.source.href

2020-12-03 11:33 UTC, gorushkin commented on src/index.js
>    const assetsFolderPath = path.join(pathToProject, assetsFolderName);
Ну так у ф-ции **convertUrlToSlugName** один функционал - конвертирование url в slug.
А в ассетах мы уже собираем имя с учетом расширения файла, пути к нему . но само имя файла таким же образом конвертируем в slug. В общем, не очень понимаю что именно надо сделать ((

2020-12-03 21:25 UTC, foofaev commented on src/index.js
>    const assetsFolderPath = path.join(pathToProject, assetsFolderName);
просто, что в ассетах, что тут один и тот же смысл - взять урлу и сделать из нее путь к файлу. ладно, наверно, оставь как есть

2020-12-03 21:26 UTC, foofaev commented on src/index.js
> +        return { ...item, source };
так а зачем добавлять? это не несет никакой пользы. есть отдельно урла, отдельно элемент дома

2020-12-04 13:00 UTC, gorushkin commented on src/index.js
> +        return { ...item, source };
ну а как тогда?
```
      .map((item) => {
        const url = (new URL(item.attribs[itemSrcAttribute], targetUrl));
        return [url, item];
      })
      .filter(([url]) => url.origin === targetUrl.origin)
      .map(([url, item]) => {
        const filename = getElementFilename(url.href);
        item.attribs[itemSrcAttribute] = path.join(assetsFolderName, filename);
        return { url, filename };
      });
```
Так?

2020-12-10 06:02 UTC, merged